export {
  computeBehaviorAnalysis,
  computeBehaviorScores,
  computeEmotionalConsistencyScore,
  computeExitBehaviorRows,
  computeMoodPerformance,
  computePersonalRuleCorrelations,
  generateBehaviorRecommendations,
  generateCoachingInsights,
  splitEntriesByPeriod,
  type BehaviorAnalysisResult,
  type BehaviorRecommendation,
  type BehaviorScoreSummary,
  type CoachingInsight,
  type ComputeBehaviorAnalysisParams,
  type ExitBehaviorRow,
  type MoodPerformanceRow,
  type PersonalRuleCorrelation,
  type RuleAdherenceMetric,
} from "@/lib/behavior/behavior-analysis";
